blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/shasikhan/css-animation-showcase#readme
    about: Check our documentation before creating an issue
  - name: 💬 Discussion
    url: https://github.com/shasikhan/css-animation-showcase/discussions
    about: Please ask and answer questions here
  - name: 🔒 Security Issue
    url: https://github.com/shasikhan/css-animation-showcase/security/policy
    about: Please report security vulnerabilities directly to the maintainers
